# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='Renderable.proto',
  package='',
  serialized_pb='\n\x10Renderable.proto\"\xe9\x02\n\nRenderable\x12\x30\n\npointCloud\x18\x01 \x01(\x0b\x32\x1c.Renderable.PointCloudXYZRGB\x12\x17\n\x0frenderableFrame\x18\x02 \x01(\t\x1a+\n\x08PointXYZ\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\x1a\x34\n\x08\x43olorRGB\x12\x0b\n\x03red\x18\x01 \x02(\x02\x12\r\n\x05green\x18\x02 \x02(\x02\x12\x0c\n\x04\x62lue\x18\x03 \x02(\x02\x1aW\n\x0bPointXYZRGB\x12#\n\x05point\x18\x01 \x02(\x0b\x32\x14.Renderable.PointXYZ\x12#\n\x05\x63olor\x18\x02 \x02(\x0b\x32\x14.Renderable.ColorRGB\x1aJ\n\x10PointCloudXYZRGB\x12\'\n\x06points\x18\x01 \x03(\x0b\x32\x17.Renderable.PointXYZRGB\x12\r\n\x05units\x18\x02 \x01(\x02*\x08\x08\x64\x10\x80\x80\x80\x80\x02')




_RENDERABLE_POINTXYZ = descriptor.Descriptor(
  name='PointXYZ',
  full_name='Renderable.PointXYZ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='Renderable.PointXYZ.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='Renderable.PointXYZ.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='z', full_name='Renderable.PointXYZ.z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=110,
  serialized_end=153,
)

_RENDERABLE_COLORRGB = descriptor.Descriptor(
  name='ColorRGB',
  full_name='Renderable.ColorRGB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='red', full_name='Renderable.ColorRGB.red', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='green', full_name='Renderable.ColorRGB.green', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blue', full_name='Renderable.ColorRGB.blue', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=155,
  serialized_end=207,
)

_RENDERABLE_POINTXYZRGB = descriptor.Descriptor(
  name='PointXYZRGB',
  full_name='Renderable.PointXYZRGB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='point', full_name='Renderable.PointXYZRGB.point', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='color', full_name='Renderable.PointXYZRGB.color', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=209,
  serialized_end=296,
)

_RENDERABLE_POINTCLOUDXYZRGB = descriptor.Descriptor(
  name='PointCloudXYZRGB',
  full_name='Renderable.PointCloudXYZRGB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='points', full_name='Renderable.PointCloudXYZRGB.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='units', full_name='Renderable.PointCloudXYZRGB.units', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=298,
  serialized_end=372,
)

_RENDERABLE = descriptor.Descriptor(
  name='Renderable',
  full_name='Renderable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pointCloud', full_name='Renderable.pointCloud', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='renderableFrame', full_name='Renderable.renderableFrame', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RENDERABLE_POINTXYZ, _RENDERABLE_COLORRGB, _RENDERABLE_POINTXYZRGB, _RENDERABLE_POINTCLOUDXYZRGB, ],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 536870912), ],
  serialized_start=21,
  serialized_end=382,
)

_RENDERABLE_POINTXYZ.containing_type = _RENDERABLE;
_RENDERABLE_COLORRGB.containing_type = _RENDERABLE;
_RENDERABLE_POINTXYZRGB.fields_by_name['point'].message_type = _RENDERABLE_POINTXYZ
_RENDERABLE_POINTXYZRGB.fields_by_name['color'].message_type = _RENDERABLE_COLORRGB
_RENDERABLE_POINTXYZRGB.containing_type = _RENDERABLE;
_RENDERABLE_POINTCLOUDXYZRGB.fields_by_name['points'].message_type = _RENDERABLE_POINTXYZRGB
_RENDERABLE_POINTCLOUDXYZRGB.containing_type = _RENDERABLE;
_RENDERABLE.fields_by_name['pointCloud'].message_type = _RENDERABLE_POINTCLOUDXYZRGB
DESCRIPTOR.message_types_by_name['Renderable'] = _RENDERABLE

class Renderable(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class PointXYZ(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RENDERABLE_POINTXYZ
    
    # @@protoc_insertion_point(class_scope:Renderable.PointXYZ)
  
  class ColorRGB(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RENDERABLE_COLORRGB
    
    # @@protoc_insertion_point(class_scope:Renderable.ColorRGB)
  
  class PointXYZRGB(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RENDERABLE_POINTXYZRGB
    
    # @@protoc_insertion_point(class_scope:Renderable.PointXYZRGB)
  
  class PointCloudXYZRGB(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RENDERABLE_POINTCLOUDXYZRGB
    
    # @@protoc_insertion_point(class_scope:Renderable.PointCloudXYZRGB)
  DESCRIPTOR = _RENDERABLE
  
  # @@protoc_insertion_point(class_scope:Renderable)

# @@protoc_insertion_point(module_scope)
